name: Builds image, pushes to registry, deploys to container app (prompts for app name)

on:
  workflow_dispatch:
    inputs:
      name:
          type: string
          description: app to build, push, and deploy
          required: true
    
jobs:
  
    call-build-deploy-container-app:
      uses: ./.github/workflows/_build_deploy_containerapp_image.yml
      with:
        app-name: ${{ github.event.inputs.name }}
      secrets:
        container_registry: ${{ secrets.container_registry }}
        container_registry_id: ${{ secrets.container_registry_id }}
        container_registry_pw: ${{ secrets.container_registry_pw }}
        azure_credentials: ${{ secrets.azure_credentials }}
  
