name: Example Workflow for Environment Files

on:
    workflow_dispatch:
        inputs:
            APP_NAME:
                type: string
                description: 'The name of the app'
                required: true
                default: 'myapp'

jobs:
  set_and_use_env_vars:
    runs-on: ubuntu-latest
    steps:

        # Checks-out your repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v2
  
      - name: Set environment variable
        run: |
            echo "MY_ENV_VAR=myValue" >> $GITHUB_ENV
            echo "MY_OTHER_VAR=otherVar" >> $GITHUB_ENV

      - name: Use environment variable
        run: |
            echo "The value of MY_ENV_VAR is $MY_ENV_VAR"
            echo "The value of MY_OTHER_VAR is $MY_OTHER_VAR"
    
            - name: Set environment variable
            run: |
              for varval in $(cat ./services/${{ inputs.APP_NAME }}/build_vars.txt);
                do
                    echo $varval >> $GITHUB_ENV
                done
    
      - name: check environment variables
        run: |
          echo "A = $A"
          echo "B = $B"
          echo "C = $C"
          echo "DD = $DD"
    