# 
# deploy UI to vercel
#

name: build & deploy UX to vercel prod

env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches: 
      - master
    paths:
      - 'ux/**'
  workflow_dispatch:

jobs:
    Deploy-vercel-Production:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./ux
        steps:
          - uses: actions/checkout@v2

          - name: Install Vercel CLI
            run: npm install --global vercel@latest

          - name: Pull Vercel Environment Information
            run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

          - name: Build Project Artifacts
            run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

          - name: Deploy Project Artifacts to Vercel
            run: vercel deploy --prod --force --token=${{ secrets.VERCEL_TOKEN }}
